env: staging
gcpProjectId: entur-ror-test
gcpDatabaseInstance: entur-ror-test:europe-west1:chouette-db-pg13=tcp:5432
gcpBucketName: ror-chouette-test
tiamatUrl: http://tiamat.tst.entur.internal
osrmRailUrl: http://osrm-rail.tst.entur.internal
osrmBusUrl: http://osrm-bus.tst.entur.internal
osrmWaterUrl: http://osrm-water.tst.entur.internal
