replicas: 3
horizontalPodAutoscaler:
  maxReplicas: 5
  minReplicas: 3

image:
  identifier: ${artifact.metadata.image}

service:
  http:
    externalPort: 80
    internalPort: 8080

resources:
  cpuLimit: "3"
  memLimit: 18000Mi
  cpuRequest: "2"
  memRequest: 17000Mi
  xmx: 15g
